In [2]:
print("hi")

hi


In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv('Desktop/Courses/DeepLearningBootcamp/Student_Marks.csv')

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lm = LinearRegression()

In [39]:
X = data[["sinif","sure"]]

In [47]:
data.head()

sinif sure     not
0     3    4  19.202
1     4    0   7.734
2     4    3  13.811
3     6    7  53.018
4     8    7  55.299

In [40]:
y = data[["not"]]

In [37]:
data[["sure"]] = data[["sure"]].astype(np.int64)

In [41]:
X

sinif sure
0      3    4
1      4    0
2      4    3
3      6    7
4      8    7
..   ...  ...
95     6    3
96     3    0
97     4    7
98     7    0
99     3    6

[100 rows x 2 columns]

In [42]:
model = lm.fit(X, y)

In [43]:
model.predict([[4,5]])

array([[29.51381349]])

In [44]:
model.coef_ #katsayilar

array([[1.99330708, 5.36188086]])

In [45]:
model.intercept_  #sabit sayi

array([-5.26881915])

In [48]:
model.predict([[3,4]])

array([[22.15862555]])

In [49]:
(1.99330708*3) + ( 5.36188086*4) +(-5.26881915)

22.158625530000002

In [76]:
model.score(X,y)

0.9308913845436668

AttributeError: 'LinearRegression' object has no attribute 'accurency'